; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Українізатор для Hitman: Blood Money"
#define MyAppVersion "2.3"
#define MyAppPublisher "romamakar"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6939CBF1-4779-46AF-BD8B-92B4F628248A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf32}\Steam\steamapps\common\Hitman Blood Money
DisableDirPage=no
;DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=HitmanBM_Ukr2_3
OutputDir=Output
SetupIconFile=D:\a\Hitman_Ukr\Hitman_Ukr\installer\installer.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Files]
Source: "D:\a\Hitman_Ukr\Hitman_Ukr\output\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename:"{app}\HitmanBloodMoney.exe"; Description:"Запустити Hitman Blood Money"; Flags: postinstall nowait shellexec

